# Generated by Django 5.2.6 on 2025-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('sheba_number', models.CharField(max_length=24, verbose_name='شماره شبا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'تنظیمات پرداخت',
                'verbose_name_plural': 'تنظیمات پرداخت',
            },
        ),
    ]
