# Generated by Django 5.2.6 on 2025-09-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'مدیر آژانس'), ('booking_agent', 'کاربر رزرو'), ('finance_manager', 'مدیر مالی'), ('viewer', 'فقط مشاهده\u200cگر')], max_length=50, unique=True, verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'نقش کاربر آژانس',
                'verbose_name_plural': 'نقش\u200cهای کاربران آژانس',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='agency_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agencyuserrole', verbose_name='نقش در آژانس'),
        ),
    ]
