# Generated by Django 5.2.7 on 2025-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: نوروز ۱۴۰۵', max_length=255, verbose_name='نام دوره')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'دوره زمانی خاص',
                'verbose_name_plural': 'دوره\u200cهای زمانی خاص',
                'ordering': ['-start_date'],
            },
        ),
    ]
