# Generated by Django 5.2.7 on 2025-12-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_specialperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, help_text='فرمت: 09123456789', max_length=11, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
