# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations
from django.conf import settings

def create_wallets_for_existing_users(apps, schema_editor):
    """
    Iterates through all existing users and creates a Wallet for each
    if one does not already exist.
    """
    # We get the model from the versioned app registry;
    # direct import of models might use a newer version than this migration expects.
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Wallet = apps.get_model('core', 'Wallet')
    
    for user in User.objects.all():
        # Using get_or_create is an idempotent and safe way to ensure
        # a wallet exists without creating duplicates.
        Wallet.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        # This should be the name of your last migration file in 'core' app.
        # Example: ('core', '0003_auto_...'), you must update this line.
        ('core', '0001_initial'), # لطفا این را به نام آخرین مایگریشن خود تغییر دهید
    ]

    operations = [
        migrations.RunPython(create_wallets_for_existing_users),
    ]
