# Generated by Django 5.2.6 on 2025-10-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wallet_wallettransaction'),
        ('core', '0005_create_wallets_for_existing_users'),
    ]

    operations = [
    ]
