# Generated by Django 5.2.6 on 2025-10-16 00:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251016_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'انجام شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='شناسه تراکنش'),
        ),
    ]
