# Generated by Django 5.2.6 on 2025-09-21 08:21

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0002_roomtype_amenities_roomtype_child_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد موجود')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'موجودی روزانه',
                'verbose_name_plural': 'موجودی\u200cهای روزانه',
                'ordering': ['date'],
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
