# Generated by Django 5.2.6 on 2025-09-24 21:28

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد موجود')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'موجودی روزانه',
                'verbose_name_plural': 'موجودی\u200cهای روزانه',
                'ordering': ['date'],
                'unique_together': {('room_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت پایه آن شب (تومان)')),
                ('extra_person_price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت نفر اضافه (تومان)')),
                ('child_price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت کودک (تومان)')),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotels.boardtype', verbose_name='نوع سرویس')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'قیمت روزانه',
                'verbose_name_plural': 'قیمت\u200cهای روزانه',
                'ordering': ['date'],
                'unique_together': {('room_type', 'date', 'board_type')},
            },
        ),
    ]
