# Generated by Django 5.2.6 on 2025-09-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
