# Generated by Django 5.2.6 on 2025-09-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام امکانات')),
            ],
            options={
                'verbose_name': 'امکانات رفاهی',
                'verbose_name_plural': 'امکانات رفاهی',
            },
        ),
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام سرویس')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد اختصاری (مثلا: BB, FB)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع سرویس',
                'verbose_name_plural': 'انواع سرویس',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام هتل')),
                ('stars', models.PositiveSmallIntegerField(default=3, verbose_name='ستاره هتل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات هتل')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='امکانات رفاهی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='hotels.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل\u200cها',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع اتاق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات نوع اتاق')),
                ('base_capacity', models.PositiveSmallIntegerField(default=2, verbose_name='ظرفیت پایه (نفر)')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه هر شب (تومان)')),
                ('extra_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت نفر اضافه')),
                ('child_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت کودک')),
                ('extra_person_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر نفر اضافه (تومان)')),
                ('child_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر کودک (تومان)')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='hotels.amenity', verbose_name='امکانات اختصاصی اتاق')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='هتل')),
            ],
            options={
                'verbose_name': 'نوع اتاق',
                'verbose_name_plural': 'انواع اتاق',
                'unique_together': {('hotel', 'name')},
            },
        ),
    ]
