# Generated by Django 5.2.7 on 2025-10-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام امکانات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenity_icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'امکانات رفاهی',
                'verbose_name_plural': 'امکانات رفاهی',
            },
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نوع تخت')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع تخت',
                'verbose_name_plural': 'انواع تخت',
            },
        ),
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام سرویس')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد اختصاری (مثلا: BB, FB)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع سرویس',
                'verbose_name_plural': 'انواع سرویس',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شهر')),
                ('slug', models.SlugField(help_text='یکتا و برای آدرس\u200cدهی مناسب سئو', unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات شهر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_landing/', verbose_name='تصویر لندینگ')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('is_featured', models.BooleanField(default=False, verbose_name='شهر برجسته')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(help_text='یکتا و برای آدرس\u200cدهی مناسب سئو', unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_categories/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی هتل',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای هتل',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته\u200cبندی اتاق')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اتاق',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اتاق',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام هتل')),
                ('slug', models.SlugField(help_text='یکتا و برای آدرس\u200cدهی مناسب سئو', unique=True, verbose_name='اسلاگ')),
                ('stars', models.PositiveSmallIntegerField(default=3, verbose_name='ستاره هتل')),
                ('is_online', models.BooleanField(default=True, help_text='در صورت فعال بودن، رزروها به صورت آنی تایید', verbose_name='رزرو آنلاین (تایید آنی)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات هتل')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('is_suggested', models.BooleanField(default=False, verbose_name='هتل پیشنهادی')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('check_in_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='زمان ورود')),
                ('check_out_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='زمان خروج')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین هتل')),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='امکانات رفاهی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='hotels.city', verbose_name='شهر')),
                ('hotel_categories', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelcategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل\u200cها',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='تصویر')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='هتل')),
            ],
            options={
                'verbose_name': 'تصویر هتل',
                'verbose_name_plural': 'تصاویر هتل',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع اتاق')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد نوع اتاق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات نوع اتاق')),
                ('base_capacity', models.PositiveSmallIntegerField(default=2, verbose_name='ظرفیت پایه (نفر)')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه هر شب (تومان)')),
                ('extra_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت نفر اضافه')),
                ('child_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت کودک')),
                ('extra_person_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر نفر اضافه (تومان)')),
                ('child_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر کودک (تومان)')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='hotels.amenity', verbose_name='امکانات اختصاصی اتاق')),
                ('bed_types', models.ManyToManyField(blank=True, related_name='room_types', to='hotels.bedtype', verbose_name='نوع تخت\u200cها')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='هتل')),
                ('room_categories', models.ManyToManyField(blank=True, related_name='room_types', to='hotels.roomcategory', verbose_name='دسته\u200cبندی\u200cهای اتاق')),
            ],
            options={
                'verbose_name': 'نوع اتاق',
                'verbose_name_plural': 'انواع اتاق',
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='تصویر')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'تصویر اتاق',
                'verbose_name_plural': 'تصاویر اتاق',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جاذبه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/', verbose_name='تصویر')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='hotels.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'جاذبه گردشگری',
                'verbose_name_plural': 'جاذبه\u200cهای گردشگری',
            },
        ),
    ]
