# Generated by Django 5.2.6 on 2025-09-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='room_types', to='hotels.amenity', verbose_name='امکانات اختصاصی اتاق'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='child_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت کودک'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='child_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر کودک (تومان)'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات نوع اتاق'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ظرفیت نفر اضافه'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_person_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر نفر اضافه (تومان)'),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('hotel', 'name')},
        ),
    ]
