# Generated by Django 5.2.7 on 2025-10-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancellations', '__first__'),
        ('hotels', '0001_initial'),
        ("cancellations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy_normal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_normal_policy', to='cancellations.cancellationpolicy', verbose_name='سیاست لغو (ایام عادی)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy_peak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_peak_policy', to='cancellations.cancellationpolicy', verbose_name='سیاست لغو (ایام پیک)'),
        ),
    ]
