# Generated by Django 5.2.6 on 2025-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_suggested',
            field=models.BooleanField(default=False, verbose_name='هتل پیشنهادی'),
        ),
    ]
