# Generated by Django 5.2.6 on 2025-09-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نوع تخت')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نوع تخت',
                'verbose_name_plural': 'انواع تخت',
            },
        ),
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(help_text='یکتا و برای آدرس\u200cدهی مناسب سئو', unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_categories/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی هتل',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای هتل',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته\u200cبندی اتاق')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اتاق',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اتاق',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات شهر'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city_landing/', verbose_name='تصویر لندینگ'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='شهر برجسته'),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='test', help_text='یکتا و برای آدرس\u200cدهی مناسب سئو', unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='زمان ورود'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='test', help_text='یکتا و برای آدرس\u200cدهی مناسب سئو', unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='code',
            field=models.CharField(default='5', max_length=20, unique=True, verbose_name='کد نوع اتاق'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_types',
            field=models.ManyToManyField(blank=True, related_name='room_types', to='hotels.bedtype', verbose_name='نوع تخت\u200cها'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_categories',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='هتل')),
            ],
            options={
                'verbose_name': 'تصویر هتل',
                'verbose_name_plural': 'تصاویر هتل',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_categories',
            field=models.ManyToManyField(blank=True, related_name='room_types', to='hotels.roomcategory', verbose_name='دسته\u200cبندی\u200cهای اتاق'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'تصویر اتاق',
                'verbose_name_plural': 'تصاویر اتاق',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جاذبه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/', verbose_name='تصویر')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='hotels.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'جاذبه گردشگری',
                'verbose_name_plural': 'جاذبه\u200cهای گردشگری',
            },
        ),
    ]
