# Generated by Django 5.2.7 on 2025-12-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_cancellation_policy_normal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TouristAttraction',
        ),
    ]
