# Generated by Django 5.2.7 on 2026-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'نوع اتاق', 'verbose_name_plural': 'انواع اتاق'},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='priority',
            field=models.IntegerField(default=0, help_text='عدد کمتر = نمایش بالاتر', verbose_name='اولویت نمایش'),
        ),
    ]
