# Generated by Django 5.2.7 on 2026-02-12 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_roomtype_options_roomtype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tax_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='عددی بین ۰ تا ۱۰۰ وارد کنید. (۰ = بدون مالیات)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات بر ارزش افزوده'),
        ),
    ]
