# Generated by Django 5.2.7 on 2025-10-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع سرویس')),
                ('requires_details', models.BooleanField(default=False, verbose_name='نیازمند اطلاعات اضافی؟')),
            ],
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سرویس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pricing_model', models.CharField(choices=[('PERSON', 'به ازای هر نفر'), ('BOOKING', 'به ازای هر رزرو'), ('FREE', 'رایگان')], max_length=10, verbose_name='مدل قیمت\u200cگذاری')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotels.hotel', verbose_name='هتل')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype', verbose_name='نوع سرویس')),
            ],
        ),
        migrations.CreateModel(
            name='BookedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ نهایی سرویس')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='جزئیات')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to='reservations.booking', verbose_name='رزرو')),
                ('hotel_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.hotelservice', verbose_name='سرویس هتل')),
            ],
        ),
    ]
