# Generated by Django 5.2.7 on 2026-02-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='is_taxable',
            field=models.BooleanField(default=True, verbose_name='مشمول مالیات است؟'),
        ),
    ]
