# Generated by Django 5.2.7 on 2025-10-17 19:13

import django.db.models.deletion
import django_jalali.db.models
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_holder', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='شماره حساب')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='شماره کارت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'حساب بانکی آفلاین',
                'verbose_name_plural': 'حساب\u200cهای بانکی آفلاین',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=reservations.models.generate_numeric_booking_code, max_length=8, unique=True, verbose_name='کد رزرو')),
                ('check_in', django_jalali.db.models.jDateField(verbose_name='تاریخ ورود')),
                ('check_out', django_jalali.db.models.jDateField(verbose_name='تاریخ خروج')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('awaiting_confirmation', 'منتظر تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('cancellation_requested', 'درخواست لغو شده'), ('modification_requested', 'درخواست ویرایش شده'), ('no_capacity', 'عدم ظرفیت')], default='pending', max_length=30, verbose_name='وضعیت')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی ارسال شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='agencies.agency', verbose_name='رزرو برای آژانس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر رزرو کننده')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='میهمان خارجی است؟')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[reservations.models.validate_iranian_national_id], verbose_name='کد ملی')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پاسپورت')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[reservations.models.validate_iranian_mobile], verbose_name='شماره تماس')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='تابعیت')),
                ('city_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر مبدأ')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'میهمان',
                'verbose_name_plural': 'میهمانان',
            },
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه موجودیت')),
                ('tracking_code', models.CharField(max_length=50, verbose_name='شماره پیگیری / ارجاع')),
                ('payment_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و ساعت پرداخت')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مبلغ واریزی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت اطلاعات')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع موجودیت')),
                ('offline_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.offlinebank', verbose_name='حساب بانکی مقصد')),
            ],
            options={
                'verbose_name': 'تاییدیه پرداخت آفلاین',
                'verbose_name_plural': 'تاییدیه پرداخت\u200cهای آفلاین',
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد اتاق')),
                ('adults', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد نفرات اضافی (بالای ظرفیت پایه)')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کودکان این اتاق')),
                ('extra_requests', models.TextField(blank=True, null=True, verbose_name='درخواست\u200cهای اضافی اتاق')),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rooms', to='hotels.boardtype', verbose_name='نوع سرویس')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='reservations.booking', verbose_name='رزرو')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rooms', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'اتاق رزرو شده',
                'verbose_name_plural': 'اتاق\u200cهای رزرو شده',
                'unique_together': {('booking', 'room_type', 'board_type')},
            },
        ),
    ]
