# Generated by Django 5.2.6 on 2025-09-21 14:43

import django.db.models.deletion
import django_jalali.db.models
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=reservations.models.generate_numeric_booking_code, max_length=8, unique=True, verbose_name='کد رزرو')),
                ('check_in', django_jalali.db.models.jDateField(verbose_name='تاریخ ورود')),
                ('check_out', django_jalali.db.models.jDateField(verbose_name='تاریخ خروج')),
                ('adults', models.PositiveSmallIntegerField(verbose_name='تعداد بزرگسالان')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کودکان')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.roomtype', verbose_name='نوع اتاق')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر رزرو کننده')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='میهمان خارجی است؟')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پاسپورت')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='تابعیت')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.booking', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'میهمان',
                'verbose_name_plural': 'میهمانان',
            },
        ),
    ]
