# Generated by Django 5.2.7 on 2025-11-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_room_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='جمع هزینه اتاق\u200cها'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_service_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='جمع هزینه خدمات'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_vat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مالیات بر ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='قیمت کل این ردیف اتاق'),
        ),
    ]
