# Generated by Django 5.2.6 on 2025-09-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_bedtype_hotelcategory_roomcategory_city_description_and_more'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('cancellation_requested', 'درخواست لغو شده'), ('modification_requested', 'درخواست ویرایش شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد اتاق')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='reservations.booking', verbose_name='رزرو')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rooms', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'اتاق رزرو شده',
                'verbose_name_plural': 'اتاق\u200cهای رزرو شده',
                'unique_together': {('booking', 'room_type')},
            },
        ),
    ]
