# Generated by Django 5.2.6 on 2025-09-21 15:05

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[reservations.models.validate_iranian_national_id], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[reservations.models.validate_iranian_mobile], verbose_name='شماره تماس'),
        ),
    ]
