# Generated by Django 5.2.7 on 2025-11-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_cancellation_policy_normal_and_more'),
        ('reservations', '0002_booking_paid_amount_booking_total_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinebank',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='اگر خالی باشد، این حساب برای همه هتل\u200cها نمایش داده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel', verbose_name='اختصاص به هتل (اختیاری)'),
        ),
        migrations.AddField(
            model_name='offlinebank',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True, verbose_name='شماره شبا (IR)'),
        ),
    ]
