# Generated by Django 5.2.6 on 2025-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_guest_national_id_alter_guest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='اطلاع\u200cرسانی ارسال شده؟'),
        ),
    ]
