# Generated by Django 5.2.6 on 2025-09-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='adults',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد نفرات اضافی (بالای ظرفیت پایه)'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کودکان این اتاق'),
        ),
    ]
