# Generated by Django 5.2.6 on 2025-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_booking_adults_remove_booking_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
