# Generated by Django 5.2.7 on 2026-02-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_offlinebank_hotel_offlinebank_shaba_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='tracking_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره پیگیری / ارجاع'),
        ),
    ]
