# Generated by Django 5.2.7 on 2026-02-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_paymentconfirmation_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('awaiting_confirmation', 'منتظر تایید'), ('awaiting_completion', 'در انتظار تکمیل وجه'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('cancellation_requested', 'درخواست لغو شده'), ('modification_requested', 'درخواست ویرایش شده'), ('no_capacity', 'عدم ظرفیت')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
    ]
