# Generated by Django 5.2.6 on 2025-10-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='extra_requests',
            field=models.TextField(blank=True, null=True, verbose_name='درخواست\u200cهای اضافی اتاق'),
        ),
        migrations.AddField(
            model_name='guest',
            name='city_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر مبدأ'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی'),
        ),
    ]
