# Generated by Django 5.2.6 on 2025-10-11 23:46

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_bookingroom_extra_requests_guest_city_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_holder', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='شماره حساب')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='شماره کارت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'حساب بانکی آفلاین',
                'verbose_name_plural': 'حساب\u200cهای بانکی آفلاین',
            },
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, verbose_name='شماره پیگیری / ارجاع')),
                ('payment_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و ساعت پرداخت')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مبلغ واریزی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت اطلاعات')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmation', to='reservations.booking', verbose_name='رزرو')),
                ('offline_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.offlinebank', verbose_name='حساب بانکی مقصد')),
            ],
            options={
                'verbose_name': 'تاییدیه پرداخت آفلاین',
                'verbose_name_plural': 'تاییدیه پرداخت\u200cهای آفلاین',
            },
        ),
    ]
