# Generated by Django 5.2.6 on 2025-10-16 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reservations', '0006_offlinebank_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentconfirmation',
            name='booking',
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع موجودیت'),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه موجودیت'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('awaiting_confirmation', 'منتظر تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('cancellation_requested', 'درخواست لغو شده'), ('modification_requested', 'درخواست ویرایش شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
    ]
