# Generated by Django 5.2.7 on 2025-10-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام سیاست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات (اختیاری)')),
            ],
            options={
                'verbose_name': 'سیاست لغو',
                'verbose_name_plural': '۱. سیاست\u200cهای لغو',
            },
        ),
        migrations.CreateModel(
            name='CancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_checkin_min', models.PositiveIntegerField(help_text='شروع بازه زمانی. مثال: 7 (برای 7 تا 14 روز قبل از ورود)', verbose_name='حداقل روز (شروع بازه)')),
                ('days_before_checkin_max', models.PositiveIntegerField(help_text='پایان بازه زمانی. مثال: 14 (برای 7 تا 14 روز قبل از ورود). برای یک روز خاص، هر دو را یکسان بگذارید.', verbose_name='حداکثر روز (پایان بازه)')),
                ('penalty_type', models.CharField(choices=[('PERCENT_TOTAL', 'درصد از کل مبلغ رزرو'), ('PERCENT_FIRST_NIGHT', 'درصد از هزینه شب اول'), ('FIXED_NIGHTS', 'تعداد ثابت شب اقامت')], max_length=30, verbose_name='نوع جریمه')),
                ('penalty_value', models.DecimalField(decimal_places=2, help_text="اگر نوع 'درصد' است، عددی بین 0 تا 100 (مثال: 70.0). اگر 'تعداد شب' است، (مثال: 1.0).", max_digits=10, verbose_name='مقدار جریمه')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cancellations.cancellationpolicy', verbose_name='سیاست مرتبط')),
            ],
            options={
                'verbose_name': 'قانون لغو',
                'verbose_name_plural': '۲. قوانین لغو (جزئیات)',
                'ordering': ['policy', 'days_before_checkin_min'],
                'unique_together': {('policy', 'days_before_checkin_min', 'days_before_checkin_max')},
            },
        ),
    ]
