"""
Django settings for reservation_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)x$4f&e7e-%u)cid2&v!i)q$ulxoyg=kxc)=m_n^789mtfhy7^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['192.168.10.131','2.180.44.137','demo.mirisafar.com']
CORS_ALLOWED_ORIGINS = [
    # آدرس بک‌اند فعلی (که قبلا به عنوان baseURL تعریف کردید)
    "https://demo.mirisafar.com",
    "http://demo.mirisafar.com",
    
    # آدرس اصلی که فرانت‌اند از آن به API دسترسی پیدا می‌کند (بسیار حیاتی)
    # این همان آدرسی است که در تصویر Network دیده می‌شود:
    "http://hotel.mirisafar.com", 
    
    # آدرس لوکال شما (برای توسعه):
    "http://192.168.10.131:3000",
    "http://localhost:3000", 
    
    # اگر از HTTPS برای فرانت‌اند استفاده می‌کنید:
    "https://hotel.mirisafar.com", 
]

# 2. به‌روزرسانی CSRF (برای فرم‌های POST و احراز هویت)
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
# Application definition

# reservation_system/settings.py

INSTALLED_APPS = [
    'jalali_date',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core.apps.CoreConfig',
    'hotels.apps.HotelsConfig',
    'pricing.apps.PricingConfig',
    'agencies.apps.AgenciesConfig',
    'reservations.apps.ReservationsConfig',
    'rest_framework.authtoken',
    'notifications.apps.NotificationsConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- اینجا اضافه شود (اولویت اول)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reservation_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reservation_system.wsgi.application'

#CustomUser 

AUTH_USER_MODEL = 'core.CustomUser'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#django-jalali
JALALI_DATE_DEFAULTS = {
   'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'StaticFiles': False,
}

# CELERY SETTINGS
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

STATICFILES_DIRS = [BASE_DIR / 'static']
