# Generated by Django 5.2.6 on 2025-09-21 16:34

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0002_alter_guest_national_id_alter_guest_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام آژانس')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='فرد رابط')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='سقف اعتبار (تومان)')),
                ('current_balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='بدهی فعلی (تومان)')),
            ],
            options={
                'verbose_name': 'آژانس',
                'verbose_name_plural': 'آژانس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AgencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('booking', 'رزرو اعتباری'), ('payment', 'پرداخت/تسویه'), ('adjustment', 'اصلاح حساب')], max_length=20, verbose_name='نوع تراکنش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agencies.agency', verbose_name='آژانس')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.booking', verbose_name='رزرو مرتبط')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت توسط')),
            ],
            options={
                'verbose_name': 'تراکنش مالی آژانس',
                'verbose_name_plural': 'تراکنش\u200cهای مالی آژانس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع قرارداد')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان قرارداد')),
                ('contract_type', models.CharField(choices=[('dynamic', 'درصد تخفیف'), ('static', 'قیمت ثابت')], max_length=10, verbose_name='نوع قرارداد')),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, help_text='فقط برای قراردادهای درصد تخفیف', null=True, verbose_name='درصد تخفیف')),
                ('static_rates', models.JSONField(blank=True, help_text='فقط برای قراردادهای قیمت ثابت. مثال: {"room_type_id_1": 250000}', null=True, verbose_name='نرخ\u200cهای ثابت')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agencies.agency', verbose_name='آژانس')),
                ('credit_blacklist_hotels', models.ManyToManyField(blank=True, related_name='blacklisted_contracts', to='hotels.hotel', verbose_name='هتل\u200cهای لیست سیاه اعتباری')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hotels.hotel', verbose_name='هتل')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
    ]
