# Generated by Django 5.2.6 on 2025-09-24 21:28

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان قرارداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات قرارداد')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع قرارداد')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان قرارداد')),
                ('contract_type', models.CharField(choices=[('dynamic', 'درصد تخفیف'), ('static', 'نرخ ثابت')], max_length=10, verbose_name='نوع قرارداد')),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, help_text='فقط برای قراردادهای درصد تخفیف', null=True, verbose_name='درصد تخفیف')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
            },
        ),
        migrations.CreateModel(
            name='StaticRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه (تومان)')),
                ('extra_person_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت نفر اضافه (تومان)')),
                ('child_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت کودک (تومان)')),
            ],
            options={
                'verbose_name': 'نرخ ثابت',
                'verbose_name_plural': 'نرخ\u200cهای ثابت',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام آژانس')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='فرد رابط')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='سقف اعتبار (تومان)')),
                ('current_balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='بدهی فعلی (تومان)')),
                ('default_discount_percentage', models.PositiveSmallIntegerField(default=0, help_text='در صورتی که قراردادی برای هتل یافت نشود، این تخفیف اعمال می\u200cشود', verbose_name='درصد تخفیف پیش\u200cفرض')),
                ('credit_blacklist_hotels', models.ManyToManyField(blank=True, to='hotels.hotel', verbose_name='هتل\u200cهای لیست سیاه اعتباری')),
            ],
            options={
                'verbose_name': 'آژانس',
                'verbose_name_plural': 'آژانس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AgencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('booking', 'رزرو اعتباری'), ('payment', 'پرداخت/تسویه'), ('adjustment', 'اصلاح حساب')], max_length=20, verbose_name='نوع تراکنش')),
                ('transaction_date', django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ تراکنش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری/تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agencies.agency', verbose_name='آژانس')),
            ],
            options={
                'verbose_name': 'تراکنش مالی آژانس',
                'verbose_name_plural': 'تراکنش\u200cهای مالی آژانس',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
