# Generated by Django 5.2.6 on 2025-09-21 17:05

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencytransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'تراکنش مالی آژانس', 'verbose_name_plural': 'تراکنش\u200cهای مالی آژانس'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='static_rates',
        ),
        migrations.AddField(
            model_name='agency',
            name='default_discount_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='در صورتی که قراردادی برای هتل یافت نشود، این تخفیف اعمال می\u200cشود', verbose_name='درصد تخفیف پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='agencytransaction',
            name='transaction_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ تراکنش'),
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='قرارداد عمومی', max_length=255, verbose_name='عنوان قرارداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('dynamic', 'درصد تخفیف'), ('static', 'نرخ ثابت')], max_length=10, verbose_name='نوع قرارداد'),
        ),
        migrations.CreateModel(
            name='StaticRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت پایه (تومان)')),
                ('extra_person_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت نفر اضافه (تومان)')),
                ('child_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت کودک (تومان)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_rates', to='agencies.contract', verbose_name='قرارداد')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_rates', to='hotels.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'نرخ ثابت',
                'verbose_name_plural': 'نرخ\u200cهای ثابت',
                'unique_together': {('contract', 'room_type')},
            },
        ),
    ]
