# Generated by Django 5.2.6 on 2025-09-24 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('hotels', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.booking', verbose_name='رزرو مرتبط'),
        ),
        migrations.AddField(
            model_name='agencytransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت توسط'),
        ),
        migrations.AddField(
            model_name='contract',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agencies.agency', verbose_name='آژانس'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hotels.hotel', verbose_name='هتل'),
        ),
        migrations.AddField(
            model_name='staticrate',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_rates', to='agencies.contract', verbose_name='قرارداد'),
        ),
        migrations.AddField(
            model_name='staticrate',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_rates', to='hotels.roomtype', verbose_name='نوع اتاق'),
        ),
        migrations.AlterUniqueTogether(
            name='staticrate',
            unique_together={('contract', 'room_type')},
        ),
    ]
