# Generated by Django 5.2.6 on 2025-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytransaction',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری/تراکنش'),
        ),
    ]
