# Generated by Django 5.2.6 on 2025-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agencyuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-priority'], 'verbose_name': 'قرارداد', 'verbose_name_plural': 'قراردادها'},
        ),
        migrations.AddField(
            model_name='contract',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='قرارداد با عدد بالاتر، اولویت بیشتری دارد', verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='staticrate',
            name='child_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر کودک (تومان)'),
        ),
        migrations.AlterField(
            model_name='staticrate',
            name='extra_person_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر نفر اضافه (تومان)'),
        ),
    ]
