# Generated by Django 5.2.7 on 2025-12-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0003_delete_touristattraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='attraction_categories/', verbose_name='آیکون (نشانگر نقشه)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی جاذبه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای جاذبه',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام جاذبه')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه (برای کارت)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
                ('suggested_duration', models.CharField(blank=True, help_text='مثال: ۲ تا ۳ ساعت', max_length=50, null=True, verbose_name='مدت پیشنهادی بازدید')),
                ('best_visit_time', models.CharField(blank=True, choices=[('morning', 'صبح'), ('afternoon', 'بعد از ظهر'), ('evening', 'غروب/شب'), ('full_day', 'تمام روز')], max_length=20, null=True, verbose_name='بهترین زمان بازدید')),
                ('entry_fee', models.DecimalField(decimal_places=0, default=0, help_text='۰ به معنی رایگان', max_digits=12, verbose_name='هزینه ورودی (تومان)')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='امتیاز')),
                ('is_featured', models.BooleanField(default=False, verbose_name='جاذبه برجسته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='hotels.city', verbose_name='شهر')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='attractions.attractioncategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'جاذبه گردشگری',
                'verbose_name_plural': 'جاذبه\u200cهای گردشگری',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ImageField(upload_to='attraction_images/', verbose_name='تصویر')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر کاور؟')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction', verbose_name='جاذبه')),
            ],
            options={
                'verbose_name': 'تصویر جاذبه',
                'verbose_name_plural': 'گالری تصاویر جاذبه',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
