# Generated by Django 5.2.7 on 2025-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractioncategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='attractioncategory',
            name='icon_name',
            field=models.CharField(default='MapPin', help_text='نام دقیق آیکون را از وب\u200cسایت Lucide.dev کپی و اینجا وارد کنید (مثال: Landmark, Mountain, Ticket).', max_length=100, verbose_name='نام آیکون (Lucide)'),
        ),
    ]
