# Generated by Django 5.2.7 on 2025-12-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_remove_attractioncategory_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='امکان رفاهی')),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام آیکون (اختیاری)')),
            ],
            options={
                'verbose_name': 'امکان رفاهی جاذبه',
                'verbose_name_plural': 'امکانات رفاهی جاذبه',
            },
        ),
        migrations.CreateModel(
            name='AttractionAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='گروه مخاطب')),
            ],
            options={
                'verbose_name': 'گروه مخاطب',
                'verbose_name_plural': 'گروه\u200cهای مخاطب (مناسب برای)',
            },
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='suggested_duration',
        ),
        migrations.AddField(
            model_name='attraction',
            name='categories',
            field=models.ManyToManyField(related_name='attractions', to='attractions.attractioncategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='visiting_hours',
            field=models.CharField(blank=True, help_text='مثال: همه روزه از ۹ صبح تا ۱۷ عصر', max_length=255, null=True, verbose_name='ساعات بازدید'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='attractioncategory',
            name='icon_name',
            field=models.CharField(default='MapPin', help_text='نام دقیق آیکون را از وب\u200cسایت Lucide.dev کپی کنید.', max_length=100, verbose_name='نام آیکون (Lucide)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='attractions.attractionamenity', verbose_name='امکانات رفاهی'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='audiences',
            field=models.ManyToManyField(blank=True, to='attractions.attractionaudience', verbose_name='مناسب برای'),
        ),
    ]
