# Generated by Django 5.2.7 on 2025-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100, verbose_name='نام سرویس\u200cدهنده (مثلا: ایمیل اصلی)')),
                ('host', models.CharField(max_length=255, verbose_name='هاست (Host)')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='پورت (Port)')),
                ('username', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('use_tls', models.BooleanField(default=True, verbose_name='استفاده از TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='استفاده از SSL')),
                ('is_active', models.BooleanField(default=False, help_text='تنها یک کانفیگ می\u200cتواند فعال باشد.', verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'تنظیمات ایمیل',
                'verbose_name_plural': 'تنظیمات ایمیل',
            },
        ),
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='فراز اس\u200cام\u200cاس', max_length=100, verbose_name='نام سرویس\u200cدهنده')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید API')),
                ('sender_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره خط ارسال\u200cکننده')),
                ('is_active', models.BooleanField(default=False, help_text='تنها یک کانفیگ می\u200cتواند فعال باشد.', verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
    ]
